site_name: Max FIchtl
site_url: https://max-fic.github.io/site/
repo_url: https://github.com/max-fic/site

theme:
  name: material
  palette:
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
  features:
    - navigation.tabs
    - navigation.indexes
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy

plugins:
  - search
  - tags
  - blog:
      blog_dir: blog
      post_date_format: medium
      archive: true

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark # For ==highlighting==
  - pymdownx.keys # For ++key++ boxes
  - pymdownx.betterem # Recommended for better emphasis handling
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - md_in_html
  - tables
  - footnotes
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - path: javascripts/mathjax.js
    defer: true
  - path: https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
    defer: true

